services:
  freenet:
    container_name: freenet
    image: thanhlam00290/freenet:latest
    restart: unless-stopped
    ports:
      - "8888:80"
      - "9999:8888"
      - "12345:12345/udp"
      - "12346:12346/udp"
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./download:/download
    environment:
      - allowedhosts=127.0.0.1,0:0:0:0:0:0:0:1
      - darknetport=12345
      - opennetport=12346
      - PUID=1000
      - PGID=1000
